### ISSUE TITLE
Bean Counter Sales Pitch

### ISSUE THREAD

**Issue by amberauthier** [entaxy-project/bean-counter#15]

**Comment by JackNeto** [comment]
Will I run out of money before I die?

**Comment by amberauthier** [comment]
Maximize your net worth buy using your money efficiently.

**Comment by Abaxial** [comment]
Through the labyrinth.
Ball of yarn.
Woven threads.

The shortest path through the labyrinth.

(http://www.creativitypost.com/arts/myth_and_creativity_ariadnes_thread_and_a_path_through_the_labyrinth)

Something along the lines of cutting through the complexity and labyrinthine nature of interconnected finances to get to the heart of the matter.  The centre of the maze, your net worth, and the potential it allows for growth.

**Comment by Abaxial** [comment]
Clarity

**Comment by Abaxial** [comment]
Regroup

**Comment by JackNeto** [comment]
Abacus

**Comment by Abaxial** [comment]
Nebulo (Nice word, sounds great, memorable, negative connotation)
Refract
Refraction (Refraction showing possibility from source, reveals all contained colours, true meaning, the span of possibility)

**Comment by Abaxial** [comment]
accessible, appreciable, blatant, bright, certain, clear, comprehensible, defined, definite, determined, direct, distinct, evident, exact, explicit, fathomable, firm, intelligible, knowable, legible, obvious, palpable, patent, pellucid, plain, self-evident, self-explanatory, straightforward, strong, sure, tangible, unambiguous, understandable, unequivocal, unmistakable, visible, nonambiguous.

**Comment by Abaxial** [comment]
Diffraction, which occurs when a wave encounters an obstacle and propagates around it.

"All it takes the will to act, the rest is just data."

**Comment by kamalsaleh2** [comment]
All it takes is a first step, the rest is entaxy
